
# è¡¨æƒ…åŒ…
emoji:
  # '+1': ğŸ‘
  # '-1': ğŸ‘
  # '100': ğŸ’¯
  # '1234': ğŸ”¢
  # '1st_place_medal': ğŸ¥‡
  # '2nd_place_medal': ğŸ¥ˆ
  # '3rd_place_medal': ğŸ¥‰
  # '8ball': ğŸ±
  # 'a': ğŸ…°ï¸
  # 'ab': ğŸ†
  # 'abc': ğŸ”¤
  # 'abcd': ğŸ”¡
  # 'Accept': ğŸ‰‘
  # 'aerial_tramway': ğŸš¡
  # 'alien': ğŸ‘½
  # 'angel': ğŸ‘¼
  # 'angry': ğŸ˜ 
  # 'anguished': ğŸ˜§
  # 'apple': ğŸ
  # 'astonished': ğŸ˜²
  # 'baby': ğŸ‘¶
  # 'baby_bottle': ğŸ¼
